package com.ssm.entity;

import java.io.Serializable;

public class DataControl implements Serializable{
    /** 
	 * @description: 
	 * @version 1.0
	 * @author IMANON
	 * @createDate 2014-1-19;下午10:51:09
	 */
	private static final long serialVersionUID = -2962829274664955135L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_data_control.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_data_control.control
     *
     * @mbggenerated
     */
    private String control;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_data_control.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_data_control.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_data_control.id
     *
     * @return the value of security_data_control.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_data_control.id
     *
     * @param id the value for security_data_control.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_data_control.control
     *
     * @return the value of security_data_control.control
     *
     * @mbggenerated
     */
    public String getControl() {
        return control;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_data_control.control
     *
     * @param control the value for security_data_control.control
     *
     * @mbggenerated
     */
    public void setControl(String control) {
        this.control = control == null ? null : control.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_data_control.description
     *
     * @return the value of security_data_control.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_data_control.description
     *
     * @param description the value for security_data_control.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_data_control.name
     *
     * @return the value of security_data_control.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_data_control.name
     *
     * @param name the value for security_data_control.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}